# Basic Information 
title: Mahmudul Hoque
position: M.S. in Advanced Computing
affiliation: Morgan State University
email: mahoq1@morgan.edu

# Search Engine Optimization (SEO)
keywords: Mahmudul Hoque, Morgan State University, Artificial Intelligence, Medical Imaging, Generative AI, Multimodal Learning, Deep Learning, Radiology AI
description: Mahmudul Hoque is a graduate researcher in Advanced Computing at Morgan State University, focusing on Generative AI, multimodal models, and medical image analysis.
canonical: https://yourusername.github.io/ # Replace with your actual GitHub Pages URL

# Links 
google_scholar: https://scholar.google.com/citations?user=VLEeZg8AAAAJ&hl=en
cv_link: assets/files/mahmudul_hoque_cv.pdf # Make sure to upload the CV here
github_link: https://github.com/ # Replace with your actual GitHub profile
linkedin: https://www.linkedin.com/in/mahmudul-hoque-40504595/
twitter: https://twitter.com/ # Optional: Replace if you use Twitter

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

# Google Analytics ID
# google_analytics: UA-XXXXXXX-X  # Replace if you use analytics or remove this line

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
